name: Workflow

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Checar o repositório
        uses: actions/checkout@v3

      - name: Registrar evento
        run: echo "Workflow executado! Commit ou Pull Request detectado."
